name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
firebase_core: 0.3.1+1
assets:
    -assets/
    
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  font_awesome_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
